[[education]]
period = "2023.09 - Present"
institution = "Harbin Institute of Technology, Shenzhen"
degree = "B.Arch., Architecture"
advisor = "Prof. Yongxi Gong"

[[education]]
period = "2025.09 - 2026.08"
institution = "Harbin Institute of Technology"
degree = "Exchange Student"
advisor = "Associate Prof. Lulu Chen"